<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="C:\Users\dasha\OneDrive\Документы\учеба\архитектуры\практическая 1.cs" Link="практическая 1.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WorkoutApp.Model\WorkoutApp.Model.csproj" />
  </ItemGroup>

</Project>